spring.application.name=classifieds-lifecycle

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/kleinanzeigen
spring.datasource.username=postgres
spring.datasource.password=fennpfuhl

# Hibernate
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG