
name: Scraper build
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      run:   ./gradlew :scraper:jibBuild --image=ghcr.io/tschy/classifieds-scraper:$(date +"%y%m%d-%H%M%S")
