

name: build and deploy
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch: 
  
permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: kleinanzeigen_test
          POSTGRES_PASSWORD: fennpfuhl
        ports:
          - 5433:5432
        # This ensures GitHub waits until the DB is ready before starting your tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and test analyzer
      run: ./gradlew :analysis:build

    - name: Build scraper and push image
      run: ./gradlew :scraper:jib --image=ghcr.io/tschy/classifieds-scraper:${{ github.run_number }}


        
